import type { TemplateDefinition } from "../types";

export const atelierTemplate: TemplateDefinition = {
  meta: {
    id: "atelier",
    name: "Atelier Studio",
    description: "Elegante y sofisticado para salones de belleza y spas. Lujo accesible en cada detalle.",
    category: "Belleza & Bienestar",
    thumbnailGradient: "from-rose-50 via-pink-100 to-stone-100",
    accentColor: "#d4a5a5",
  },
  defaults: {
    brand: {
      name: "Atelier Studio",
      tagline: "Belleza que te transforma",
      logoUrl: "",
      phone: "+54 11 6666-7777",
      email: "turnos@atelierstudio.com.ar",
      address: "Palermo Soho, Buenos Aires",
      whatsapp: "+5491166667777",
    },
    colors: {
      primary: "#faf8f3",
      accent: "#c9956c",
      surface: "#f5f0e8",
      text: "#2d2d2d",
      textMuted: "#8b7355",
      ctaText: "#ffffff",
    },
    hero: {
      badge: "Salón de belleza & spa",
      title: "Donde la belleza",
      titleAccent: "es un ritual",
      subtitle: "Tratamientos premium para cabello, piel y bienestar. Porque merecés sentirte increíble cada día.",
      ctaPrimary: "Reservar turno",
      ctaPrimaryUrl: "#contacto",
      ctaSecondary: "Ver servicios",
      ctaSecondaryUrl: "#servicios",
      imageUrl: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1920&q=80",
    },
    about: {
      enabled: true,
      title: "Un espacio pensado para vos",
      body: "Somos un equipo de profesionales apasionados por la belleza y el bienestar. Cada tratamiento es personalizado, usando solo productos de primera línea en un ambiente diseñado para que te desconectes del mundo.",
      imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
      stats: [
        { value: "8 años", label: "De trayectoria" },
        { value: "2.500+", label: "Clientas felices" },
        { value: "12", label: "Especialistas" },
        { value: "5 ⭐", label: "En Google" },
      ],
    },
    services: {
      enabled: true,
      title: "Nuestros servicios",
      subtitle: "Tratamientos profesionales para cada necesidad",
      items: [
        { icon: "✂️", title: "Corte & Peinado", description: "Cortes de vanguardia, brushings y peinados para toda ocasión.", price: "desde $8.500" },
        { icon: "🎨", title: "Color & Mechas", description: "Balayage, mechas californianas, coloración orgánica. Sin daño.", price: "desde $18.000" },
        { icon: "💆", title: "Tratamientos capilares", description: "Keratina, botox capilar, hidratación profunda y más.", price: "desde $12.000" },
        { icon: "💅", title: "Manicura & Pedicura", description: "Uñas acrílicas, semipermanente, nail art y spa de pies.", price: "desde $6.000" },
        { icon: "🧖", title: "Faciales & Spa", description: "Limpieza profunda, hialu­rón, radiofrecuencia y masajes.", price: "desde $15.000" },
        { icon: "👁️", title: "Diseño de cejas & Pestañas", description: "Laminado, tinte, extensiones y microblading.", price: "desde $9.000" },
      ],
    },
    gallery: {
      enabled: true,
      title: "Nuestro trabajo",
      images: [
        { url: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80", alt: "Balayage" },
        { url: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=600&q=80", alt: "Maquillaje artístico" },
        { url: "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=600&q=80", alt: "Tratamiento capilar" },
        { url: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&q=80", alt: "Nail art" },
        { url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80", alt: "Facial spa" },
        { url: "https://images.unsplash.com/photo-1610992015732-2449b76344bc?w=600&q=80", alt: "Peinado" },
      ],
    },
    contact: {
      enabled: true,
      title: "Reservá tu turno",
      subtitle: "Te respondemos en menos de una hora. También podés escribirnos por WhatsApp.",
      showPhone: true,
      showEmail: true,
      showAddress: true,
      showForm: true,
    },
    social: { instagram: "", facebook: "", whatsapp: "+5491166667777", tiktok: "" },
    footer: { text: "© 2026 Atelier Studio. Todos los derechos reservados." },
  },
};
