import type { TemplateDefinition } from "../types";

export const autodriveTemplate: TemplateDefinition = {
  meta: {
    id: "autodrive",
    name: "AutoDrive",
    description: "Diseño oscuro y premium para concesionarias. Destaca tus vehículos con estética de lujo.",
    category: "Automotriz",
    thumbnailGradient: "from-slate-900 via-blue-950 to-slate-900",
    accentColor: "#d4af37",
  },
  defaults: {
    brand: {
      name: "AutoDrive Premium",
      tagline: "Tu vehículo de ensueño te espera",
      logoUrl: "",
      phone: "+54 11 4444-5555",
      email: "ventas@autodrive.com.ar",
      address: "Av. del Libertador 4500, Buenos Aires",
      whatsapp: "+5491144445555",
    },
    colors: {
      primary: "#0a0e27",
      accent: "#d4af37",
      surface: "#1a1f3a",
      text: "#ffffff",
      textMuted: "#94a3b8",
      ctaText: "#0a0e27",
    },
    hero: {
      badge: "Concesionaria oficial",
      title: "Manejá el auto que",
      titleAccent: "siempre soñaste",
      subtitle: "Más de 500 unidades disponibles. Financiación en el acto, entrega inmediata.",
      ctaPrimary: "Ver catálogo",
      ctaPrimaryUrl: "#catalogo",
      ctaSecondary: "Agendar test drive",
      ctaSecondaryUrl: "#contacto",
      imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1920&q=80",
    },
    about: {
      enabled: true,
      title: "Más de 20 años en el mercado automotor",
      body: "Somos una concesionaria familiar con tradición y compromiso. Nuestro equipo de asesores te acompaña desde la elección del vehículo hasta la entrega de las llaves, con transparencia y sin sorpresas.",
      imageUrl: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&q=80",
      stats: [
        { value: "500+", label: "Vehículos en stock" },
        { value: "12.000+", label: "Clientes satisfechos" },
        { value: "20 años", label: "De trayectoria" },
        { value: "3 sedes", label: "En Buenos Aires" },
      ],
    },
    services: {
      enabled: true,
      title: "Todo lo que necesitás en un solo lugar",
      subtitle: "Desde la compra hasta el mantenimiento, te cubrimos.",
      items: [
        { icon: "💳", title: "Financiación propia", description: "Tasas preferenciales sin banco. Aprobación en 24 hs.", price: "Desde 0% de anticipo" },
        { icon: "🔧", title: "Service oficial", description: "Taller propio con técnicos certificados por fábrica.", price: "Turno online" },
        { icon: "🛡️", title: "Garantía extendida", description: "Hasta 3 años de garantía total en unidades nuevas.", price: "Incluida" },
        { icon: "🔄", title: "Tomamos tu usado", description: "Valuación justa e inmediata. Lo tomamos a cuenta.", price: "Sin burocracia" },
        { icon: "🚗", title: "Test drive", description: "Probá el vehículo antes de comprarlo. Sin compromiso.", price: "Gratis" },
        { icon: "📋", title: "Gestión de patente", description: "Nos encargamos de todos los trámites por vos.", price: "Incluida" },
      ],
    },
    gallery: {
      enabled: true,
      title: "Algunos de nuestros destacados",
      images: [
        { url: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&q=80", alt: "Vehículo deportivo" },
        { url: "https://images.unsplash.com/photo-1542362567-b07e54358753?w=600&q=80", alt: "SUV premium" },
        { url: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600&q=80", alt: "Sedán ejecutivo" },
        { url: "https://images.unsplash.com/photo-1485291571150-772bcfc10da5?w=600&q=80", alt: "Cupé de lujo" },
        { url: "https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=600&q=80", alt: "Eléctrico moderno" },
        { url: "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=600&q=80", alt: "Pick-up premium" },
      ],
    },
    contact: {
      enabled: true,
      title: "¿Listo para empezar?",
      subtitle: "Completá el formulario y un asesor te contacta en menos de 2 horas.",
      showPhone: true,
      showEmail: true,
      showAddress: true,
      showForm: true,
    },
    social: { instagram: "", facebook: "", whatsapp: "+5491144445555", tiktok: "" },
    footer: { text: "© 2026 AutoDrive Premium. Todos los derechos reservados." },
  },
};
