import type { TemplateDefinition } from "../types";

export const wanderlustTemplate: TemplateDefinition = {
  meta: {
    id: "wanderlust",
    name: "WanderlustCo",
    description: "Cálido y aventurero para coordinadores de viajes. Inspira a tus clientes a explorar el mundo.",
    category: "Turismo & Viajes",
    thumbnailGradient: "from-amber-100 via-orange-200 to-rose-200",
    accentColor: "#c67c4e",
  },
  defaults: {
    brand: {
      name: "WanderlustCo",
      tagline: "Cada viaje, una historia",
      logoUrl: "",
      phone: "+54 11 5555-6666",
      email: "hola@wanderlustco.com.ar",
      address: "Florida 520, Buenos Aires",
      whatsapp: "+5491155556666",
    },
    colors: {
      primary: "#fef3e2",
      accent: "#c67c4e",
      surface: "#fff8f0",
      text: "#1c1c1e",
      textMuted: "#6b7280",
      ctaText: "#ffffff",
    },
    hero: {
      badge: "Coordinador de viajes",
      title: "Tu próxima aventura",
      titleAccent: "te está esperando",
      subtitle: "Diseñamos viajes únicos a medida. Desde escapadas de fin de semana hasta travesías internacionales.",
      ctaPrimary: "Ver destinos",
      ctaPrimaryUrl: "#destinos",
      ctaSecondary: "Consultar gratis",
      ctaSecondaryUrl: "#contacto",
      imageUrl: "https://images.unsplash.com/photo-1488085061387-422e29b40080?w=1920&q=80",
    },
    about: {
      enabled: true,
      title: "Viajamos desde 2010, creamos recuerdos para siempre",
      body: "Somos un equipo apasionado por los viajes con más de 15 años organizando experiencias inolvidables. Conocemos cada destino de primera mano y trabajamos con los mejores proveedores locales para que tu viaje sea perfecto.",
      imageUrl: "https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=800&q=80",
      stats: [
        { value: "3.200+", label: "Viajeros felices" },
        { value: "48", label: "Países cubiertos" },
        { value: "15 años", label: "De experiencia" },
        { value: "4.9 ⭐", label: "Valoración promedio" },
      ],
    },
    services: {
      enabled: true,
      title: "Destinos que te van a enamorar",
      subtitle: "Paquetes diseñados para cada tipo de viajero",
      items: [
        { icon: "🏔️", title: "Aventura & Trekking", description: "Patagonia, Aconcagua, Torres del Paine. Para los que buscan adrenalina.", price: "desde $180.000" },
        { icon: "🏖️", title: "Playas & Relax", description: "Caribe, Brasil, Bali. Paraísos tropicales todo incluido.", price: "desde $250.000" },
        { icon: "🏛️", title: "Cultural & City Trips", description: "Europa, Japón, Marruecos. Historia, arte y gastronomía.", price: "desde $320.000" },
        { icon: "🍷", title: "Enoturismo", description: "Mendoza, Rioja, Toscana. Bodegas, catas y paisajes de viñedos.", price: "desde $95.000" },
        { icon: "🚢", title: "Cruceros", description: "Mediterráneo, Alaska, Antártida. Todo incluido en alta mar.", price: "desde $400.000" },
        { icon: "💑", title: "Luna de Miel", description: "Viajes románticos diseñados especialmente para parejas.", price: "desde $200.000" },
      ],
    },
    gallery: {
      enabled: true,
      title: "Momentos que nuestros viajeros no olvidan",
      images: [
        { url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80", alt: "Playa paradisíaca" },
        { url: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&q=80", alt: "Montañas nevadas" },
        { url: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=600&q=80", alt: "Ciudad histórica" },
        { url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80", alt: "Viaje de montaña" },
        { url: "https://images.unsplash.com/photo-1504019347908-b45f9b0b8dd5?w=600&q=80", alt: "Destino exótico" },
        { url: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&q=80", alt: "Ruta de aventura" },
      ],
    },
    contact: {
      enabled: true,
      title: "Contanos dónde querés ir",
      subtitle: "Nuestros asesores te arman el itinerario perfecto. Sin costo, sin compromiso.",
      showPhone: true,
      showEmail: true,
      showAddress: true,
      showForm: true,
    },
    social: { instagram: "", facebook: "", whatsapp: "+5491155556666", tiktok: "" },
    footer: { text: "© 2026 WanderlustCo. Diseñado para viajeros que quieren más." },
  },
};
